version: "3.8"

services:
  evaluate_resume_service:
    container_name: "app-evaluate-resume"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      APP_REDIS_HOST: "redis-evaluate"
      APP_GOOGLE_API_KEY: "${APP_GOOGLE_API_KEY}"
      PYTHONUNBUFFERED: "1"
    resources:
      limits:
        cpus: "0.5"
        memory: "512M"
      reservations:
        cpus: "0.25"
        memory: "256M"
    depends_on:
      - redis-evaluate
    command: [
        "gunicorn",
        "app:app", # atau "app.main:create_app()"
        "-w",
        "2",
        "--threads",
        "4",
        "--worker-class",
        "gthread", # stabil untuk I/O heavy; bisa ganti default
        "--bind",
        "0.0.0.0:8001",
        "--timeout",
        "60",
        "--graceful-timeout",
        "30",
        "--keep-alive",
        "5",
        "--max-requests",
        "1000",
        "--max-requests-jitter",
        "100",
      ]

  worker:
    container_name: "worker-evaluate"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-u", "worker.py"]
    resources:
      limits:
        cpus: "0.5"
        memory: "512M"
      reservations:
        cpus: "0.25"
        memory: "256M"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      APP_REDIS_HOST: "redis-evaluate"
      APP_GOOGLE_API_KEY: "${APP_GOOGLE_API_KEY}"
      GOOGLE_API_KEY: "${APP_GOOGLE_API_KEY}"
    depends_on:
      - redis-evaluate

  redis-evaluate:
    image: "redis:latest"
    container_name: "redis-evaluate"
    resources:
      limits:
        cpus: "0.5"
        memory: "512M"
      reservations:
        cpus: "0.25"
        memory: "256M"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data: {}
  app_data: {}
